server:
  port: 9999
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
spring:
  application:
    name: dsp-oauth2-client
  devtools:
    restart:
      enabled: false
  resources:
    add-mappings: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        preferIpAddress: true
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        tags: urlprefix-/${spring.application.name}
        instanceId: ${spring.application.name}:${server.port}
    gateway:
      httpclient:
        pool:
          type: DISABLED
      default-filters:
      - SetResponseHeader=X-Frame-Options, DENY
      routes:
      - id: auth
        uri: lb://dsp-auth-server
        order: 2
        predicates:
        - Path=/api/auth/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: access-platform
        uri: lb://dsp-access-platform
        order: 2
        predicates:
        - Path=/api/dsp/platform/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: access-consumer
        uri: lb://dsp-access-consumer
        order: 2
        predicates:
        - Path=/api/dsp/consumer/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: access-dataapi
        uri: lb://dsp-access-dataapi
        order: 2
        predicates:
        - Path=/api/dsp/dataapi/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8004/api/auth/oauth/.well-known/jwks.json
      client:
        registration:
          dsp-auth:
            client-id: oauth2-client
            client-name: oauth2-client
            client-secret: 123456
            authorization-grant-type: authorization_code
            client-authentication-method: Basic
            scope:
            - api
            - resource
            - login
            redirect-uri-template: http://localhost:8004/api/auth/oauth/authorize
            redirect-uri: http://localhost:8004/api/auth/oauth/authorize
        provider:
          dsp-auth:
            user-name-attribute: username
            authorization-uri: http://localhost:8004/api/auth/oauth/authorize
            token-uri: http://localhost:8004/api/auth/oauth/token
            user-info-uri: http://localhost:8004/api/auth/oauth/user
management:
  endpoint:
    health:
      enabled: true
    beans:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true
security:
  token:
    ignored:
      staticResources:
      - /
      - /static/**
      - /webjars/**
      - /**/*.js*
      - /**/*.css*
      - /**/*.html*
      - /**/*.ico*
      - /**/*.json*
      - /doc.html
      anyMethods:
      - /
      - /actuator/**
      - /v2/**
      - /swagger**
      - /api/auth/oauth/**
      - /api/auth/v2/api-docs
      - /api/*/*/v2/api-docs
swagger2:
  enabled: true
  resources:
  - name: gateway
    url: /v2/api-docs
    swaggerVersion: 0.1.0
  - name: auth-server
    url: /api/auth/v2/api-docs
    swaggerVersion: 0.1.0
  - name: access-platform
    url: /api/dsp/platform/v2/api-docs
    swaggerVersion: 0.1.0
  - name: access-consumer
    url: /api/dsp/consumer/v2/api-docs
    swaggerVersion: 0.1.0