server:
  address: 192.168.2.145
  port: 8008
  reactive:
    context-path: /
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
spring:
  application:
    name: dsp-cas-gateway
  resources:
    add-mappings: true
    static-locations: classpath:/webapp/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  cloud:
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: localhost:8080
        port: 8721
        heartbeat-interval-ms: 5s
      datasource: 
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-flow-rules
            file-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-degrade-rules
            file-type: json
            rule-type: degrade
        system:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-system-rules
            file-type: json
            rule-type: system
        authority:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-authority-rules
            file-type: json
            rule-type: authority
        param-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-paramflow-rules
            file-type: json
            rule-type: param-flow
#        localfile:
#          file:
#            file: classpath:sentinel/flowrule.json
#            file-type: json
#            rule-type: flow
#            charset: UTF-8
#            buf-size: 1024
#            recommend-refresh-ms: 10000
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
        heartBeatInterval: 15
        heartBeatTimeout: 30
        metadata:
          serviceName: ${spring.application.name}
          instanceId: ${spring.application.name}:${server.address}:${server.port}
    gateway:
      httpclient:
        pool:
          type: DISABLED
      default-filters:
      - SetResponseHeader=X-Frame-Options, DENY
      routes:
      - id: access-platform
        uri: lb://dsp-access-platform
        order: 2
        predicates:
        - Path=/api/dsp/platform/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: access-consumer
        uri: lb://dsp-access-consumer
        order: 2
        predicates:
        - Path=/api/dsp/consumer/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: access-dataapi
        uri: lb://dsp-access-dataapi
        order: 2
        predicates:
        - Path=/api/dsp/dataapi/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: welcome
        uri: http://${server.address}:${server.port}
        predicates:
        - Path=/
        filters:
        - RewritePath=/(?<segment>.*), /index.html
        - PreserveHostHeader
  security:
    oauth2:
      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8004/api/auth/oauth/.well-known/jwks.json
        opaquetoken:
          client-id: dsp-cas-gateway
          client-secret: 123456
          introspection-uri: http://localhost:8004/api/auth/oauth/userinfo
      client:
        registration:
          dsp-gateway:
            client-id: dsp-cas-gateway
            client-name: dsp-cas-gateway
            client-secret: 123456
            client-authentication-method: Basic
            authorization-grant-type: authorization_code
            scope: api,resource,login,read,write,trust
            redirect-uri: http://localhost:8004/api/auth/oauth/authorize
        provider:
          dsp-gateway:
            user-name-attribute: username
            authorization-uri: http://localhost:8004/api/auth/oauth/authorize
            token-uri: http://localhost:8004/api/auth/oauth/token
            user-info-uri: http://localhost:8004/api/auth/oauth/userinfo
#            jwk-set-uri: http://localhost:8004/api/auth/oauth/.well-known/jwks.json
            user-info-authentication-method: Basic
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dialect: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.82:3306/merce_83?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT&&queryTimeout=4800
    username: merce
    password: merce
management:
  metrics:
    binders:
      hystrix.enabled: false
    enable:
      system:
        cpu: false
      process: false
      logback: false
      log4j2: false
      db: false
      jvm: false
      cache: false
      gateway: false
    export:
      simple:
        enabled: false
      elastic:
        enabled: false
        host: http://localhost:9200
        index: metrics
        index-date-format: yyyy-MM
        user-name: elastic
        password: changeme
        auto-create-index: true
        batchSize: 3
        connect-timeout: 10s
  endpoint:
    health:
      enabled: true
      show-details: never
    beans:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true
    httptrace:
      enabled: true
      summarytime: 5
      timeout: 5000
    shutdown:
      enabled: false
  endpoints:
    enabled-by-default: true
    actuator:
      enabled: true
    web:
      exposure:
        include: '*'
      cors:
        max-age: 1800s
  health:
    redis:
      enabled: false
    elasticsearch:
      enabled: false
security:
  token:
    ignored:
      staticResources:
      - /
      - /static/**
      - /webjars/**
      - /**/*.js*
      - /**/*.css*
      - /**/*.html*
      - /**/*.ico*
      - /**/*.json*
      - /*.html**
      anyMethods:
      - /
      - /actuator/**
      - /v2/**
      - /swagger**
      - /swagger-resources/**
      - /api/auth/**
      - /api/dsp/dataapi/**
      - /api/auth/v2/api-docs
      - /api/*/*/v2/api-docs
  cas:
    mode: remote
    server: http://172.25.21.205:8989/cas
    #    server: http://172.25.22.176:8989/cas
    platformServer: http://172.25.21.205:30098
    #    platformServer: http://172.25.22.176:30098
    baseUrl: http://192.168.1.36:8515
    service: ${security.cas.baseUrl}/cas/login
    firstPage: ${security.cas.baseUrl}/cas/login
    whiteList: /, /cas/tickets,/static/**,/*.html,/*.js,/*.icon

swagger2:
  enabled: true
  resources:
  - name: auth-server
    url: /api/auth/v2/api-docs
    swaggerVersion: 0.1.0
  - name: access-platform
    url: /api/dsp/platform/v2/api-docs
    swaggerVersion: 0.1.0
  - name: access-consumer
    url: /api/dsp/consumer/v2/api-docs
    swaggerVersion: 0.1.0
  - name: access-dataapi
    url: /api/dsp/dataapi/v2/api-docs
    swaggerVersion: 0.1.0
  handler:
    auto-startup: true
    auto-execute: false
springfox.documentation.auto-startup: false