server:
  port: 8008
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
spring:
  web:
    locale: zh_CN
    resources:
      add-mappings: true
      static-locations: classpath:/webapp/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  cloud:
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: 192.168.1.35:8080
        port: 8721
        heartbeat-interval-ms: 5s
      datasource: 
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-flow-rules
            file-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-degrade-rules
            file-type: json
            rule-type: degrade
        system:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-system-rules
            file-type: json
            rule-type: system
        authority:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-authority-rules
            file-type: json
            rule-type: authority
        param-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr:127.0.0.1:8848}
            group-id: ${spring.application.name}
            data-id: ${spring.application.name}-paramflow-rules
            file-type: json
            rule-type: param-flow
#        localfile:
#          file:
#            file: classpath:sentinel/flowrule.json
#            file-type: json
#            rule-type: flow
#            charset: UTF-8
#            buf-size: 1024
#            recommend-refresh-ms: 10000
    nacos:
      config:
        enabled: true
        file-extension: yaml
        namespace: yjw
        group: dsp
        prefix: ${spring.application.name}
        server-addr: 192.168.1.82:8848
      discovery:
        enabled: true
        server-addr: 192.168.1.82:8848
        namespace: yjw
        group: dsp
    gateway:
      httpclient:
        pool:
          type: DISABLED
      default-filters:
      - SetResponseHeader=X-Frame-Options, DENY
      routes:
      - id: auth-server
        uri: lb://dsp-auth-server
        order: 2
        predicates:
        - Path=/api/auth/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: access-platform
        uri: lb://dsp-access-platform
        order: 2
        predicates:
        - Path=/api/dsp/platform/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: access-consumer
        uri: lb://dsp-access-consumer
        order: 2
        predicates:
        - Path=/api/dsp/consumer/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: access-dataapi
        uri: lb://dsp-access-dataapi
        order: 2
        predicates:
        - Path=/api/dsp/dataapi/**
        filters:
        - PreserveHostHeader
        - RemoveRequestHeader=Expect
      - id: welcome
        #        uri: http://${server.address}:${server.port}
        uri: lb://${spring.application.name}
        predicates:
        - Path=/
        filters:
        - RewritePath=/(?<segment>.*), /index.html
        - PreserveHostHeader
  security:
    oauth2:
      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8004/api/auth/oauth/.well-known/jwks.json
        opaquetoken:
          client-id: dsp-gateway
          client-secret: 123456
          introspection-uri: http://localhost:8004/api/auth/oauth/userinfo
      client:
        registration:
          dsp-gateway:
            client-id: dsp-gateway
            client-name: dsp-gateway
            client-secret: 123456
            client-authentication-method: Basic
            authorization-grant-type: authorization_code
            scope: api,resource,login,read,write,trust
            redirect-uri: http://localhost:8004/api/auth/oauth/authorize
        provider:
          dsp-gateway:
            user-name-attribute: username
            authorization-uri: http://localhost:8004/api/auth/oauth/authorize
            token-uri: http://localhost:8004/api/auth/oauth/token
            user-info-uri: http://localhost:8004/api/auth/oauth/userinfo
#            jwk-set-uri: http://localhost:8004/api/auth/oauth/.well-known/jwks.json
            user-info-authentication-method: Basic
management:
  metrics:
    enable:
      system:
        cpu: false
      process: false
      logback: false
      log4j2: false
      db: false
      jvm: false
      cache: false
      gateway: false
    export:
      simple:
        enabled: false
      elastic:
        enabled: false
        host: http://localhost:9200
        index: metrics
        index-date-format: yyyy-MM
        user-name: elastic
        password: changeme
        auto-create-index: true
        batchSize: 3
        connect-timeout: 10s
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true
    httptrace:
      enabled: true
      summarytime: 5
      timeout: 5000
    shutdown:
      enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
      cors:
        max-age: 1800s
  health:
    redis:
      enabled: false
    elasticsearch:
      enabled: false
    db:
      enabled: true
security:
  token:
    ignored:
      staticResources:
      - /
      - /webjars/**
      - /css/**
      - /error/**
      - /fonts/**
      - /img/**
      - /js/**
      - /static/**
      - /sub/**
      - /*/*.js
      - /*/*.css
      - /*/*.html
      - /*/*.json
      - /*.ico
      - /*.icon
      - /*.html
      - /*.json
      anyMethods:
      - /
      - /actuator/**
      - /v2/**
      - /swagger**
      - /swagger-resources/**
      - /api/auth/**
      - /api/dsp/dataapi/**
      - /api/auth/v2/api-docs
      - /api/*/*/v2/api-docs
swagger2:
  enabled: true
  resources:
  - name: auth-server
    url: /api/auth/v2/api-docs
    swaggerVersion: 0.1.0
  - name: access-platform
    url: /api/dsp/platform/v2/api-docs
    swaggerVersion: 0.1.0
  - name: access-consumer
    url: /api/dsp/consumer/v2/api-docs
    swaggerVersion: 0.1.0
  - name: access-dataapi
    url: /api/dsp/dataapi/v2/api-docs
    swaggerVersion: 0.1.0
  handler:
    auto-startup: true
    auto-execute: false
springfox.documentation.auto-startup: false