server:
  address: 192.168.2.145
  port: 8000
spring:
  application:
    name: woven-dsp-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    consul:
      host: 192.168.2.145
      port: 8500
      discovery:
        register: true
        hostname: 192.168.2.145
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        tags: urlprefix-/${spring.application.name}
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    gateway:
      httpclient:
        pool:
          type: DISABLED
      routes:
        - id: auth-server
          uri: lb://192.168.2.145:8004
          order: 2
          predicates:
            - Path=/api/auth/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader:Expect
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
    connection-request-timeout-millis: 60000
    time-unit: seconds
  routes:
    auth:
      path: /api/auth/**
      sensitive-headers: '*'
      service-id: woven-dsp-auth-server
      stripPrefix: false
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true
  ratelimit:
    key-prefix: dsp-ratelimite
    enabled: true
    behind-proxy: true
    default-policy:
      limit: 100
      quota: 100
      refresh-interval: 3
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      serviceId: ${spring.application.name}
      user-info-uri: http://localhost:8004/api/auth/oauth/user
      prefer-token-info: false
    client:
      access-token-uri: http://localhost:8004/api/auth/oauth/token
      user-authorization-uri: http://localhost:8004/api/auth/oauth/authorize
      client-id: dsp
      client-secret: 123456
  token:
    ignored:
      staticResources:
        - /
        - /static/**
        - /webjars/**
        - /**/*.js*
        - /**/*.css*
        - /**/*.html*
        - /**/*.ico*
        - /**/*.json*
      anyMethods:
        - /
        - /actuator/**
        - /v2/**
        - /swagger**
        - /api/auth/**
swagger2:
  enabled: true
  resources:
    - name: gateway
      url: /v2/api-docs
      swaggerVersion: 0.1.0
    - name: auth-server
      url: /api/auth/v2/api-docs
      swaggerVersion: 0.1.0