apiVersion: apps/v1
kind: Deployment
metadata:
  name: baymax-dsp-access-consumer-deployment
  labels:
    app: baymax-dsp-access-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baymax-dsp-access-consumer
  template:
    metadata:
      labels:
        app: baymax-dsp-access-consumer
    spec:
      imagePullSecrets:
        - name: baymax-secret
      containers:
        - name: baymax-dsp-access-consumer
          image: 192.168.1.74/baymax/baymax-dsp-access-consumer
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: -server -Xmx1024m -Xms1024m -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -DWOVEN_COM_NAME=dsp-access-consumer -DWOVEN_LOGS_DIR=/logs -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -Dfile.encoding=UTF-8  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8400
          envFrom:
            - configMapRef:
                name: baymax-dsp-env-config
          volumeMounts:
            - name: conf
              mountPath: /baymax/conf
            - name: logs
              mountPath: /baymax/logs                
          ports:
            - containerPort: 8080
            - containerPort: 8400
          readinessProbe:
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 50
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 50
            httpGet:
              path: /actuator/health/liveness
              port: 8080
      volumes:
        - name: conf
          nfs:
            server: 192.168.1.149            
            path: /nfs/baymax/conf
        - name: logs
          hostPath:
            path: /data/baymax/logs              