---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: baymax
  name: baymax-dsp-ui-deployment
  labels:
    app: baymax-dsp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baymax-dsp-ui
  template:
    metadata:
      labels:
        app: baymax-dsp-ui
    spec:
      imagePullSecrets:
        - name: baymax-secret
      containers:
        - name: woven-gateway
          image: 192.168.1.74/baymax/dsp:latest
          imagePullPolicy: Always
          env:
            - name: HOSTS
              value: '192.168.1.149:30002'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: baymax-dsp-ui-service
spec:
  type: NodePort
  selector:
    app: baymax-dsp-ui
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30005