apiVersion: apps/v1
kind: Deployment
metadata:
  name: baymax-dsp-job-exec-deployment
  labels:
    app: baymax-dsp-job-exec
spec:
  replicas: 3
  selector:
    matchLabels:
      app: baymax-dsp-job-exec
  template:
    metadata:
      labels:
        app: baymax-dsp-job-exec
    spec:
      imagePullSecrets:
        - name: baymax-secret
      containers:
        - name: baymax-dsp-job-exec
          image: 192.168.1.74/baymax/baymax-dsp-job-exec
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: -server -Xmx1024m -Xms1024m -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -DWOVEN_COM_NAME=dsp-job-exec -DWOVEN_LOGS_DIR=/logs -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -Dfile.encoding=UTF-8
          envFrom:
            - configMapRef:
                name: baymax-dsp-env-config
          ports:
            - containerPort: 8006
          readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 30
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 30
            httpGet:
              path: /actuator/health/liveness
              port: 8080