---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baymax-dsp-ui-deploy
  namespace: dsp
  labels:
    app: baymax-dsp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baymax-dsp-ui
  template:
    metadata:
      labels:
        app: baymax-dsp-ui
    spec:
      imagePullSecrets:
        - name: dsp-secret
      containers:
        - name: woven-gateway
          image: 192.168.1.74/baymax/dsp:latest
          imagePullPolicy: Always
          env:
            - name: HOSTS
#              value: '192.168.1.149:30002'
              value: 'baymax-dsp-gateway-svc:8080'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: baymax-dsp-ui-svc
  namespace: dsp
spec:
  type: NodePort
  selector:
    app: baymax-dsp-ui
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30005