server:
  port: 8002
spring:
  zipkin:
    base-url: http://localhost:8008
  sleuth:
    sampler:
      probability: 1
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbwfny-auth?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 300
  cache:
    type: ehcache
    cache-names:
    - tempCache
    - customCache
    - captchaCache
    - persistentCache
    - securityCache
    ehcache:
      config: classpath:extends/cache/ehcache/ehcache.xml
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
swagger:
  enable: true
tx-lcn:
  logger:
    enabled: false
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.16.26:3306/dbwfny-tx?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  client:
    manager-address:
    - 192.168.16.26:8070
    tx-manager-heart: 30
    dtx-time: 36000
    dtx-aspect-order: 0
    resource-order: 0
  message:
    netty:
      wait-time: 3600